package hibernate.merlin_hibernate.dao.Interface;

import java.util.List;

import hibernate.merlin_hibernate.Entities.CompartmentsAnnotationPsortReportsHasCompartments;


public interface ICompartmentsAnnotationPsortReportsHasCompartmentsDAO {
	
	public void addCompartmentsAnnotationPsortReportsHasCompartment(CompartmentsAnnotationPsortReportsHasCompartments CompartmentsAnnotationPsortReportsHasCompartment); 
	
	public void addCompartmentsAnnotationPsortReportsHasCompartments(List<CompartmentsAnnotationPsortReportsHasCompartments> CompartmentsAnnotationPsortReportsHasCompartments); 
	
	public List<CompartmentsAnnotationPsortReportsHasCompartments> getAllCompartmentsAnnotationPsortReportsHasCompartments(); 
	
	public CompartmentsAnnotationPsortReportsHasCompartments getCompartmentsAnnotationPsortReportsHasCompartment(Integer id); 
	
	public void removeCompartmentsAnnotationPsortReportsHasCompartment(CompartmentsAnnotationPsortReportsHasCompartments CompartmentsAnnotationPsortReportsHasCompartment); 
	
	public void removeCompartmentsAnnotationPsortReportsHasCompartments(List<CompartmentsAnnotationPsortReportsHasCompartments> CompartmentsAnnotationPsortReportsHasCompartments); 
	
	public void updateCompartmentsAnnotationPsortReportsHasCompartments(List<CompartmentsAnnotationPsortReportsHasCompartments> CompartmentsAnnotationPsortReportsHasCompartments); 
	
	public void updateCompartmentsAnnotationPsortReportsHasCompartment(CompartmentsAnnotationPsortReportsHasCompartments CompartmentsAnnotationPsortReportsHasCompartment);
}
