package hibernate.merlin_hibernate.dao.Interface;

import java.util.List;

import hibernate.merlin_hibernate.Entities.TransportersAnnotationTransportedMetabolitesDirections;


public interface ITransportersAnnotationTransportedMetabolitesDirectionsDAO {
	
	
	public void addTransportersAnnotationTransportedMetabolitesDirection(TransportersAnnotationTransportedMetabolitesDirections TransportersAnnotationTransportedMetabolitesDirection); 
	
	public void addTransportersAnnotationTransportedMetabolitesDirections(List<TransportersAnnotationTransportedMetabolitesDirections> TransportersAnnotationTransportedMetabolitesDirections); 
	
	public List<TransportersAnnotationTransportedMetabolitesDirections> getAllTransportersAnnotationTransportedMetabolitesDirections(); 
	
	public TransportersAnnotationTransportedMetabolitesDirections getTransportersAnnotationTransportedMetabolitesDirections(Integer id); 
	
	public void removeTransportersAnnotationTransportedMetabolitesDirection(TransportersAnnotationTransportedMetabolitesDirections TransportersAnnotationTransportedMetabolitesDirection); 
	
	public void removeTransportersAnnotationTransportedMetabolitesDirections(List<TransportersAnnotationTransportedMetabolitesDirections> TransportersAnnotationTransportedMetabolitesDirection); 
	
	public void updateTransportersAnnotationTransportedMetabolitesDirections(List<TransportersAnnotationTransportedMetabolitesDirections> TransportersAnnotationTransportedMetabolitesDirection); 
	
	public void updateTransportersAnnotationTransportedMetabolitesDirection(TransportersAnnotationTransportedMetabolitesDirections TransportersAnnotationTransportedMetabolitesDirection);

}
