package hibernate.merlin_hibernate.dao.Interface;

import java.util.List;

import hibernate.merlin_hibernate.Entities.TransportersAnnotationTransportSystems;


public interface ITransportersAnnotationTransportSystemsDAO {

	public void addTransportersAnnotationTransportSystem(TransportersAnnotationTransportSystems TransportersAnnotationTransportSystem); 
	
	public void addTransportersAnnotationTransportSystems(List<TransportersAnnotationTransportSystems> TransportersAnnotationTransportTypes); 
	
	public List<TransportersAnnotationTransportSystems> getAllTransportersAnnotationTransportSystems(); 
	
	public TransportersAnnotationTransportSystems getTransportersAnnotationTransportSystems(Integer id); 
	
	public void removeTransportersAnnotationTransportSystem(TransportersAnnotationTransportSystems TransportersAnnotationTransportSystem); 
	
	public void removeTransportersAnnotationTransportSystems(List<TransportersAnnotationTransportSystems> TransportersAnnotationTransportSystem); 
	
	public void updateTransportersAnnotationTransportSystems(List<TransportersAnnotationTransportSystems> TransportersAnnotationTransportSystems); 
	
	public void updateTransportersAnnotationTransportSystem(TransportersAnnotationTransportSystems TransportersAnnotationTransportSystem);

}