package Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumberrank generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecnumberrank", catalog = "merlin_basic2")
public class EnzymesAnnotationEcnumberrank implements java.io.Serializable {

	private EnzymesAnnotationEcnumberrankId id;
	private String ecNumber;
	private Integer rank;

	public EnzymesAnnotationEcnumberrank() {
	}

	public EnzymesAnnotationEcnumberrank(EnzymesAnnotationEcnumberrankId id) {
		this.id = id;
	}

	public EnzymesAnnotationEcnumberrank(EnzymesAnnotationEcnumberrankId id, String ecNumber, Integer rank) {
		this.id = id;
		this.ecNumber = ecNumber;
		this.rank = rank;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "SKey", column = @Column(name = "s_key", nullable = false)),
			@AttributeOverride(name = "geneHomologySKey", column = @Column(name = "geneHomology_s_key", nullable = false)) })
	public EnzymesAnnotationEcnumberrankId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationEcnumberrankId id) {
		this.id = id;
	}

	@Column(name = "ecNumber", length = 16777215)
	public String getEcNumber() {
		return this.ecNumber;
	}

	public void setEcNumber(String ecNumber) {
		this.ecNumber = ecNumber;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

}
