package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnzymesAnnotationProductrank generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_productrank", catalog = "merlin_basic2")
public class EnzymesAnnotationProductrank implements java.io.Serializable {

	private EnzymesAnnotationProductrankId id;
	private String productName;
	private Integer rank;

	public EnzymesAnnotationProductrank() {
	}

	public EnzymesAnnotationProductrank(EnzymesAnnotationProductrankId id) {
		this.id = id;
	}

	public EnzymesAnnotationProductrank(EnzymesAnnotationProductrankId id, String productName, Integer rank) {
		this.id = id;
		this.productName = productName;
		this.rank = rank;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "SKey", column = @Column(name = "s_key", nullable = false)),
			@AttributeOverride(name = "geneHomologySKey", column = @Column(name = "geneHomology_s_key", nullable = false)) })
	public EnzymesAnnotationProductrankId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationProductrankId id) {
		this.id = id;
	}

	@Column(name = "productName", length = 65535)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

}
