package Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumberrankHasOrganism generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecnumberrank_has_organism", catalog = "merlin_basic2")
public class EnzymesAnnotationEcnumberrankHasOrganism implements java.io.Serializable {

	private EnzymesAnnotationEcnumberrankHasOrganismId id;

	public EnzymesAnnotationEcnumberrankHasOrganism() {
	}

	public EnzymesAnnotationEcnumberrankHasOrganism(EnzymesAnnotationEcnumberrankHasOrganismId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ecNumberRankSKey", column = @Column(name = "ecNumberRank_s_key", nullable = false)),
			@AttributeOverride(name = "organismSKey", column = @Column(name = "organism_s_key", nullable = false)) })
	public EnzymesAnnotationEcnumberrankHasOrganismId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationEcnumberrankHasOrganismId id) {
		this.id = id;
	}

}
