package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumberlist generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecnumberlist", catalog = "merlin_basic2")
public class EnzymesAnnotationEcnumberlist implements java.io.Serializable {

	private Integer SKey;
	private int homologyDataSKey;
	private String otherEcnumbers;

	public EnzymesAnnotationEcnumberlist() {
	}

	public EnzymesAnnotationEcnumberlist(int homologyDataSKey) {
		this.homologyDataSKey = homologyDataSKey;
	}

	public EnzymesAnnotationEcnumberlist(int homologyDataSKey, String otherEcnumbers) {
		this.homologyDataSKey = homologyDataSKey;
		this.otherEcnumbers = otherEcnumbers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "s_key", unique = true, nullable = false)
	public Integer getSKey() {
		return this.SKey;
	}

	public void setSKey(Integer SKey) {
		this.SKey = SKey;
	}

	@Column(name = "homologyData_s_key", nullable = false)
	public int getHomologyDataSKey() {
		return this.homologyDataSKey;
	}

	public void setHomologyDataSKey(int homologyDataSKey) {
		this.homologyDataSKey = homologyDataSKey;
	}

	@Column(name = "otherECNumbers", length = 16777215)
	public String getOtherEcnumbers() {
		return this.otherEcnumbers;
	}

	public void setOtherEcnumbers(String otherEcnumbers) {
		this.otherEcnumbers = otherEcnumbers;
	}

}
