package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelTranscriptionUnitGeneId generated by hbm2java
 */
@Embeddable
public class ModelTranscriptionUnitGeneId implements java.io.Serializable {

	private int transcriptionUnitIdtranscriptionUnit;
	private int geneIdgene;

	public ModelTranscriptionUnitGeneId() {
	}

	public ModelTranscriptionUnitGeneId(int transcriptionUnitIdtranscriptionUnit, int geneIdgene) {
		this.transcriptionUnitIdtranscriptionUnit = transcriptionUnitIdtranscriptionUnit;
		this.geneIdgene = geneIdgene;
	}

	@Column(name = "transcription_unit_idtranscription_unit", nullable = false)
	public int getTranscriptionUnitIdtranscriptionUnit() {
		return this.transcriptionUnitIdtranscriptionUnit;
	}

	public void setTranscriptionUnitIdtranscriptionUnit(int transcriptionUnitIdtranscriptionUnit) {
		this.transcriptionUnitIdtranscriptionUnit = transcriptionUnitIdtranscriptionUnit;
	}

	@Column(name = "gene_idgene", nullable = false)
	public int getGeneIdgene() {
		return this.geneIdgene;
	}

	public void setGeneIdgene(int geneIdgene) {
		this.geneIdgene = geneIdgene;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelTranscriptionUnitGeneId))
			return false;
		ModelTranscriptionUnitGeneId castOther = (ModelTranscriptionUnitGeneId) other;

		return (this.getTranscriptionUnitIdtranscriptionUnit() == castOther.getTranscriptionUnitIdtranscriptionUnit())
				&& (this.getGeneIdgene() == castOther.getGeneIdgene());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTranscriptionUnitIdtranscriptionUnit();
		result = 37 * result + this.getGeneIdgene();
		return result;
	}

}
