package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelCompartment generated by hbm2java
 */
@Entity
@Table(name = "model_compartment", catalog = "merlin_basic2")
public class ModelCompartment implements java.io.Serializable {

	private Integer idcompartment;
	private String name;
	private String abbreviation;

	public ModelCompartment() {
	}

	public ModelCompartment(String name, String abbreviation) {
		this.name = name;
		this.abbreviation = abbreviation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompartment", unique = true, nullable = false)
	public Integer getIdcompartment() {
		return this.idcompartment;
	}

	public void setIdcompartment(Integer idcompartment) {
		this.idcompartment = idcompartment;
	}

	@Column(name = "name", length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "abbreviation", length = 20)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

}
