package Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelSubunit generated by hbm2java
 */
@Entity
@Table(name = "model_subunit", catalog = "merlin_basic2")
public class ModelSubunit implements java.io.Serializable {

	private ModelSubunitId id;

	public ModelSubunit() {
	}

	public ModelSubunit(ModelSubunitId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "geneIdgene", column = @Column(name = "gene_idgene", nullable = false)),
			@AttributeOverride(name = "enzymeProteinIdprotein", column = @Column(name = "enzyme_protein_idprotein", nullable = false)),
			@AttributeOverride(name = "enzymeEcnumber", column = @Column(name = "enzyme_ecnumber", nullable = false, length = 15)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id")),
			@AttributeOverride(name = "proteinComplexIdproteinComplex", column = @Column(name = "protein_complex_idprotein_complex")),
			@AttributeOverride(name = "note", column = @Column(name = "note", length = 45)),
			@AttributeOverride(name = "gprStatus", column = @Column(name = "gpr_status", length = 45)) })
	public ModelSubunitId getId() {
		return this.id;
	}

	public void setId(ModelSubunitId id) {
		this.id = id;
	}

}
