package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelModuleHasOrthology generated by hbm2java
 */
@Entity
@Table(name = "model_module_has_orthology", catalog = "merlin_basic2")
public class ModelModuleHasOrthology implements java.io.Serializable {

	private ModelModuleHasOrthologyId id;

	public ModelModuleHasOrthology() {
	}

	public ModelModuleHasOrthology(ModelModuleHasOrthologyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)),
			@AttributeOverride(name = "orthologyId", column = @Column(name = "orthology_id", nullable = false)) })
	public ModelModuleHasOrthologyId getId() {
		return this.id;
	}

	public void setId(ModelModuleHasOrthologyId id) {
		this.id = id;
	}

}
