package Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelPathwayHasModule generated by hbm2java
 */
@Entity
@Table(name = "model_pathway_has_module", catalog = "merlin_basic2")
public class ModelPathwayHasModule implements java.io.Serializable {

	private ModelPathwayHasModuleId id;

	public ModelPathwayHasModule() {
	}

	public ModelPathwayHasModule(ModelPathwayHasModuleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pathwayIdpathway", column = @Column(name = "pathway_idpathway", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)) })
	public ModelPathwayHasModuleId getId() {
		return this.id;
	}

	public void setId(ModelPathwayHasModuleId id) {
		this.id = id;
	}

}
