package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelProteinComposition generated by hbm2java
 */
@Entity
@Table(name = "model_protein_composition", catalog = "merlin_basic2")
public class ModelProteinComposition implements java.io.Serializable {

	private ModelProteinCompositionId id;

	public ModelProteinComposition() {
	}

	public ModelProteinComposition(ModelProteinCompositionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "proteinIdprotein", column = @Column(name = "protein_idprotein", nullable = false)),
			@AttributeOverride(name = "subunit", column = @Column(name = "subunit", nullable = false)) })
	public ModelProteinCompositionId getId() {
		return this.id;
	}

	public void setId(ModelProteinCompositionId id) {
		this.id = id;
	}

}
