package Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelProteinComplex generated by hbm2java
 */
@Entity
@Table(name = "model_protein_complex", catalog = "merlin_basic2")
public class ModelProteinComplex implements java.io.Serializable {

	private int idproteinComplex;
	private String name;

	public ModelProteinComplex() {
	}

	public ModelProteinComplex(int idproteinComplex) {
		this.idproteinComplex = idproteinComplex;
	}

	public ModelProteinComplex(int idproteinComplex, String name) {
		this.idproteinComplex = idproteinComplex;
		this.name = name;
	}

	@Id

	@Column(name = "idprotein_complex", unique = true, nullable = false)
	public int getIdproteinComplex() {
		return this.idproteinComplex;
	}

	public void setIdproteinComplex(int idproteinComplex) {
		this.idproteinComplex = idproteinComplex;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
