package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransportersAnnotationGenes generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_genes", catalog = "merlin_basic2")
public class TransportersAnnotationGenes implements java.io.Serializable {

	private Integer id;
	private int projectId;
	private String locusTag;
	private String status;

	public TransportersAnnotationGenes() {
	}

	public TransportersAnnotationGenes(int projectId, String locusTag, String status) {
		this.projectId = projectId;
		this.locusTag = locusTag;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "locus_tag", nullable = false, length = 45)
	public String getLocusTag() {
		return this.locusTag;
	}

	public void setLocusTag(String locusTag) {
		this.locusTag = locusTag;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
