package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TransportersIdentificationSwSimilarities generated by hbm2java
 */
@Entity
@Table(name = "transporters_identification_sw_similarities", catalog = "merlin_basic2")
public class TransportersIdentificationSwSimilarities implements java.io.Serializable {

	private TransportersIdentificationSwSimilaritiesId id;
	private Float similarity;

	public TransportersIdentificationSwSimilarities() {
	}

	public TransportersIdentificationSwSimilarities(TransportersIdentificationSwSimilaritiesId id) {
		this.id = id;
	}

	public TransportersIdentificationSwSimilarities(TransportersIdentificationSwSimilaritiesId id, Float similarity) {
		this.id = id;
		this.similarity = similarity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "swReportId", column = @Column(name = "sw_report_id", nullable = false)),
			@AttributeOverride(name = "swHitId", column = @Column(name = "sw_hit_id", nullable = false)) })
	public TransportersIdentificationSwSimilaritiesId getId() {
		return this.id;
	}

	public void setId(TransportersIdentificationSwSimilaritiesId id) {
		this.id = id;
	}

	@Column(name = "similarity", precision = 12, scale = 0)
	public Float getSimilarity() {
		return this.similarity;
	}

	public void setSimilarity(Float similarity) {
		this.similarity = similarity;
	}

}
